Repository SDU-mobile-dev-2023-4/android, pull requests merged in 2023-11, with the labels that each got.

#5 Changed phone input to mail input visually
  app/src/main/java/dk/sdu/weshare/pages/ProfilePage.kt
Labels: enhancement

#16 Update save buttons to use popBackStack()
  app/src/main/java/dk/sdu/weshare/MainActivity.kt
  app/src/main/java/dk/sdu/weshare/pages/GroupDetailsPage.kt
  app/src/main/java/dk/sdu/weshare/pages/GroupsPage.kt
  app/src/main/java/dk/sdu/weshare/pages/ProfilePage.kt
Labels: bug

#17 uomi logo is inserted into sign in and register page.
  app/src/main/java/dk/sdu/weshare/pages/RegisterPage.kt
  app/src/main/java/dk/sdu/weshare/pages/SignInPage.kt
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/uomi_logo.xml
Labels: documentation

#44 43 removeuserfromgroup has a body though its a delete request
  app/src/main/java/dk/sdu/weshare/api/Api.kt
  app/src/main/java/dk/sdu/weshare/api/ApiEndpoints.kt
  app/src/main/java/dk/sdu/weshare/api/requests/RemoveUserFromGroupRequest.kt
Labels: GroupDetailsPage
